//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Camion
    {
        public Camion()
        {
            this.Pesajes = new HashSet<Pesaje>();
        }
    
        public string Placa { get; set; }
        public string Marca { get; set; }
        public int NumeroEjes { get; set; }
        [JsonIgnore]
        public virtual ICollection<Pesaje> Pesajes { get; set; }
    }
}
